<a href="https://colab.research.google.com/github/matti-mansha/pytorch/blob/main/PyTorch_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Welcome Matti! Good to see you...")

Welcome Matti! Good to see you...


In [ ]:
! nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
import torch

In [ ]:
print(torch.__version__)

1.12.1+cu113


## Introduction to Tensor

In [ ]:
# Vector
vector = torch.tensor([[[7,7], 
                       [8,8]],
                      [[5,5],
                      [1,1]]])

In [ ]:
vector

tensor([[[7, 7],
         [8, 8]],

        [[5, 5],
         [1, 1]]])

In [ ]:
vector.shape

torch.Size([2, 2, 2])

In [ ]:
vector.ndim

3

In [ ]:
vector[0][0]

tensor([7, 7])

In [ ]:
# Scalar
scalar = torch.tensor(10)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

10

## Random Tensors

In [ ]:
random_tensor = torch.rand((6, 8, 8))

In [ ]:
random_tensor

tensor([[[6.8553e-01, 7.1417e-01, 9.6362e-01, 8.6593e-01, 4.0218e-01,
          8.1678e-02, 3.0933e-02, 1.8820e-01],
         [4.0933e-01, 9.6270e-01, 5.5919e-01, 1.4436e-01, 7.1129e-01,
          6.2276e-01, 3.3577e-01, 7.0694e-02],
         [4.4004e-01, 6.8092e-01, 4.0966e-01, 3.4066e-01, 6.7125e-01,
          7.4605e-01, 8.1588e-01, 4.9164e-01],
         [6.4727e-01, 6.0480e-01, 5.9511e-01, 8.0750e-01, 5.7788e-01,
          7.3190e-01, 2.4046e-01, 6.5559e-01],
         [6.1885e-01, 5.9121e-01, 5.7220e-01, 4.7867e-01, 9.1186e-01,
          2.3022e-01, 3.4257e-01, 6.5713e-01],
         [1.4594e-01, 2.7409e-03, 9.2940e-01, 5.2420e-01, 4.9905e-02,
          3.9046e-01, 1.2427e-01, 4.5995e-01],
         [6.9588e-01, 4.2713e-02, 9.8981e-02, 4.0840e-01, 7.6233e-01,
          5.0965e-01, 8.9860e-01, 2.8328e-01],
         [3.6676e-01, 1.5939e-01, 5.1803e-01, 9.2842e-01, 5.2125e-01,
          5.1649e-01, 2.6150e-02, 2.1773e-02]],

        [[2.2079e-01, 1.3296e-01, 5.7769e-01, 8.3141e-01, 3.42

In [ ]:
random_tensor.shape

torch.Size([6, 8, 8])

In [ ]:
random_tensor.ndim

3

## Zeros and Ones

In [ ]:
zeros = torch.zeros((2, 10))

In [ ]:
zeros

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
zeros.ndim

2

In [ ]:
zeros.shape

torch.Size([2, 10])

In [ ]:
ones = torch.ones((3,7))

In [ ]:
ones

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
one_ten = torch.arange(1, 11)

In [ ]:
one_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_ten)

In [ ]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6., 9.],
                              dtype=None,
                              device=None,
                              requires_grad=False)

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# Float 32 tensor
float_16_tensor = torch.tensor([3.0, 6., 9.],
                              dtype=torch.float16,
                              device='cpu',
                              requires_grad=False)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
# casting
float_64_tensor = float_16_tensor.type(torch.float64)

In [ ]:
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [ ]:
float_64_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [ ]:
print(float_64_tensor.dtype)
print(float_64_tensor.ndim)
print(float_64_tensor.shape)
print(float_64_tensor.device)

torch.float64
1
torch.Size([3])
cpu


## Manipulating Tensors
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [ ]:
tensor = torch.tensor([1, 2, 3])

In [ ]:
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
mat1 = torch.tensor([[10, 20],
                     [40, 50]])

mat2 = torch.tensor([[11, 21],
                     [41, 51]])

In [ ]:
torch.matmul(mat1, mat2)

tensor([[ 930, 1230],
        [2490, 3390]])

In [ ]:
## Finding min, max, mean, sum, etc (tensor aggregation)

In [ ]:
x = torch.arange(0, 101, 10)

In [ ]:
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
x.min()

tensor(0)

In [ ]:
x.max()

tensor(100)

In [ ]:
x.sum()

tensor(550)

In [ ]:
torch.median(x)

tensor(50)

In [ ]:
mat1

tensor([[10, 20],
        [40, 50]])

In [ ]:
# argmin(), Position
mat1.max(dim=1)

torch.return_types.max(
values=tensor([20, 50]),
indices=tensor([1, 1]))

In [ ]:
mat1[1][1]

tensor(50)

## Reshaping, Stacking, Squeezing, Unsqueezing tensors

In [ ]:
tensor = torch.arange(1,10)

In [ ]:
x = tensor.reshape(3,3)

In [ ]:
# shares memory with x
z = x.view(1,9)

In [ ]:
z

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
torch.stack([x, x, x], dim=1)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]],

        [[7, 8, 9],
         [7, 8, 9],
         [7, 8, 9]]])

In [ ]:
torch.stack([x, x, x], dim=0)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
torch.manual_seed(123)

In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor = torch.arange(0,12).reshape(4,3)

In [ ]:
tensor_on_gpu = tensor.to(device)

In [ ]:
tensor_on_gpu

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]], device='cuda:0')

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()

In [ ]:
tensor_back_on_cpu

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])