<a href="https://colab.research.google.com/github/matti-mansha/pytorch/blob/main/PyTorch_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Welcome Matti! Good to see you...")

Welcome Matti! Good to see you...


In [ ]:
! nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
import torch

In [ ]:
print(torch.__version__)

1.12.1+cu113


## Introduction to Tensor

In [ ]:
# Vector
vector = torch.tensor([[[7,7], 
                       [8,8]],
                      [[5,5],
                      [1,1]]])

In [ ]:
vector

tensor([[[7, 7],
         [8, 8]],

        [[5, 5],
         [1, 1]]])

In [ ]:
vector.shape

torch.Size([2, 2, 2])

In [ ]:
vector.ndim

3

In [ ]:
vector[0][0]

tensor([7, 7])

In [ ]:
# Scalar
scalar = torch.tensor(10)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

10

## Random Tensors

In [ ]:
random_tensor = torch.rand((6, 8, 8))

In [ ]:
random_tensor

tensor([[[0.4923, 0.4014, 0.5124, 0.9148, 0.8604, 0.2060, 0.9075, 0.3911],
         [0.1148, 0.2188, 0.5434, 0.6814, 0.1224, 0.1488, 0.1902, 0.7029],
         [0.6469, 0.7042, 0.5508, 0.4348, 0.7042, 0.9660, 0.3090, 0.8858],
         [0.5666, 0.6371, 0.9581, 0.6622, 0.4478, 0.6330, 0.4241, 0.8705],
         [0.5539, 0.4122, 0.9020, 0.1071, 0.2182, 0.0318, 0.3667, 0.0241],
         [0.5330, 0.8719, 0.9053, 0.7226, 0.5378, 0.7310, 0.4530, 0.8565],
         [0.5561, 0.2421, 0.8157, 0.1165, 0.8288, 0.6474, 0.4222, 0.8828],
         [0.6589, 0.2241, 0.5270, 0.5739, 0.4740, 0.9905, 0.6986, 0.6137]],

        [[0.8281, 0.9071, 0.2584, 0.8847, 0.1334, 0.8738, 0.3530, 0.3932],
         [0.2375, 0.8657, 0.9790, 0.1135, 0.7679, 0.2913, 0.3129, 0.8811],
         [0.4849, 0.4648, 0.0042, 0.3503, 0.4356, 0.8271, 0.8346, 0.9377],
         [0.2942, 0.1522, 0.7262, 0.1999, 0.2222, 0.6066, 0.4194, 0.4340],
         [0.1057, 0.3297, 0.6918, 0.1971, 0.5378, 0.7560, 0.7310, 0.0289],
         [0.2803, 0.834

In [ ]:
random_tensor.shape

torch.Size([6, 8, 8])

In [ ]:
random_tensor.ndim

3

## Zeros and Ones

In [ ]:
zeros = torch.zeros((2, 10))

In [ ]:
zeros

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
zeros.ndim

2

In [ ]:
zeros.shape

torch.Size([2, 10])

In [ ]:
ones = torch.ones((3,7))

In [ ]:
ones

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
one_ten = torch.arange(1, 11)

In [ ]:
one_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_ten)

In [ ]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])